export const productos = [
    {
        categoria: "Jeans",
        nombre: "Baggy Azul Clasico",
        precio: "$39.000",
        imagen: "/productos/baggy-azul-clasico.jpeg",
        talles: "38, 40",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Black",
        precio: "$39.000",
        imagen: "/productos/baggy-black.jpeg",
        talles: "40, 42",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Bolsillos Bordados",
        precio: "$39.000",
        imagen: "/productos/baggy-bolsillos-bordados-1.jpeg",
        imagen2: "/productos/baggy-bolsillos-bordados-2.jpeg",
        talles: "40",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Cargo Azul Nevado",
        precio: "$39.000",
        imagen: "/productos/baggy-cargo-azul-nevado.jpeg",
        talles: "40",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Clasico Celeste",
        precio: "$39.000",
        imagen: "/productos/baggy-clasico-celeste.jpeg",
        talles: "42",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Costuras Blancas",
        precio: "$39.000",
        imagen: "/productos/baggy-costuras-blancas.jpeg",
        talles: "42, 46",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Cruz",
        precio: "$39.000",
        imagen: "/productos/baggy-cruz.jpeg",
        talles: "40",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Gabardina Beige",
        precio: "$39.000",
        imagen: "/productos/baggy-gabardina-beige.jpeg",
        talles: "42",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Gabardina Color Nuez",
        precio: "$39.000",
        imagen: "/productos/baggy-gabardina-color-nuez.jpeg",
        talles: "42",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Localizado Bigotes",
        precio: "$39.000",
        imagen: "/productos/baggy-localizado-bigotes.jpeg",
        talles: "40",
    },
    {
        categoria: "Jeans",
        nombre: "Jeans Baggy Bolsillos Bordado",
        precio: "$39.000",
        imagen: "/productos/jeans-baggy-bolsillos-bordado-1.jpeg",
        imagen2: "/productos/jeans-baggy-bolsillos-bordado-2.jpeg",
        imagen3: "/productos/jeans-baggy-bolsillos-bordado-3.jpeg",
        talles: "38",
    },

    {
        categoria: "Buzos",
        nombre: "Buzo Boxy Gris",
        precio: "$40.000",
        imagen: "/productos/buzo-boxy-gris.jpeg",
        talles: "L",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Clasico Alternative",
        precio: "$38.000",
        imagen: "/productos/buzo-clasico-alternative-1.jpeg",
        imagen2: "/productos/buzo-clasico-alternative-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Corazon",
        precio: "$38.000",
        imagen: "/productos/buzo-corazon.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over Blossom",
        precio: "$38.000",
        imagen: "/productos/buzo-over-blossom.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over Boxing Club",
        precio: "$40.000",
        imagen: "/productos/buzo-over-boxing-club-1.jpeg",
        imagen2: "/productos/buzo-over-boxing-club-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over Japon",
        precio: "$40.000",
        imagen: "/productos/buzo-over-japon-1.jpeg",
        imagen2: "/productos/buzo-over-japon-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over La",
        precio: "$40.000",
        imagen: "/productos/buzo-over-la.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over New York 99",
        precio: "$40.000",
        imagen: "/productos/buzo-over-new-york-99-1.jpeg",
        imagen2: "/productos/buzo-over-new-york-99-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over Speak Thut",
        precio: "$40.000",
        imagen: "/productos/buzo-over-speak-thuth-1.jpeg",
        imagen2: "/productos/buzo-over-speak-thuth-2.jpeg",
        talles: "L",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over White",
        precio: "$38.000",
        imagen: "/productos/buzo-over-white.jpeg",
        talles: "S",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over Ne",
        precio: "$34.000",
        imagen: "/productos/buzo-over-ne-1.jpeg",
        imagen2: "/productos/buzo-over-ne-2.jpeg",
        talles: "xl",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over Myself",
        precio: "$40.000",
        imagen: "/productos/buzo-over-myself.jpeg",
        talles: "L",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over Rosa",
        precio: "$38.000",
        imagen: "/productos/buzo-over-rosa-1.jpeg",
        imagen2: "/productos/buzo-over-rosa-2.jpeg",
        talles: "s",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over Stree",
        precio: "$40.000",
        imagen: "/productos/buzo-over-stree-1.jpeg",
        imagen2: "/productos/buzo-over-stree-2.jpeg",
        talles: "S",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over Nevado",
        precio: "$35.000",
        imagen: "/productos/buzo-nevado-rustico.jpeg",
        talles: "2",
    },
    {
        categoria: "Buzos",
        nombre: "Sweter Waffle black",
        precio: "$22.500",
        imagen: "/productos/sweter-waffle-black.jpeg",
        talles: "2, 3",
    },
    {
        categoria: "Buzos",
        nombre: "Sweter Waffle Plush",
        precio: "$36.000",
        imagen: "/productos/sweter-waffle-plush.jpeg",
        talles: "2",
    },
    {
        categoria: "Buzos",
        nombre: "Sweter White",
        precio: "$22.500",
        imagen: "/productos/sweter-white.jpeg",
        talles: "2",
    },
    {
        categoria: "Buzos",
        nombre: "Campera Camuflada Semi Jeans",
        precio: "$45.000",
        imagen: "/productos/campera-camuflada-semi-jeans.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Campera Reversible",
        precio: "$50.000",
        imagen: "/productos/campera-reversible-1.jpeg",
        imagen2: "/productos/campera-reversible-2.jpeg",
        talles: "S",
    },
    {
        categoria: "Buzos",
        nombre: "Campera Bomber Boxy",
        precio: "$40.000",
        imagen: "/productos/campera-bomber-boxy-jeans-1.jpeg",
        imagen2: "/productos/campera-bomber-boxy-jeans-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Chomba Boxy Alemania",
        precio: "$25.000",
        imagen: "/productos/chomba-boxy-alemania.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "remera boxy fresh",
        precio: "$24.000",
        imagen: "/productos/remera-boxy-fresh.jpeg",
        talles: "s",
    },
    {
        categoria: "Remeras",
        nombre: "Chomba Boxy Good",
        precio: "$25.000",
        imagen: "/productos/chomba-boxy-good.jpeg",
        talles: "S",
    },
    {
        categoria: "Remeras",
        nombre: "Chomba Boxy Portugal",
        precio: "$25.000",
        imagen: "/productos/chomba-boxy-portugal.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Chomba Boxy Algodon Chnyouu",
        precio: "$24.000",
        imagen: "/productos/chomba-boxy-algodon-chnyouu.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Boxy 2023",
        precio: "$18.000",
        imagen: "/productos/boxy-2023.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Boxy Corazon",
        precio: "$24.000",
        imagen: "/productos/boxy-corazon-1.jpeg",
        imagen2: "/productos/boxy-corazon-2.jpeg",
        talles: "S",
    },
    {
        categoria: "Remeras",
        nombre: "Boxy Emestudios",
        precio: "$19.000",
        imagen: "/productos/boxy-emestudios.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Boxy Energy",
        precio: "$19.000",
        imagen: "/productos/boxy-energy-1.jpeg",
        imagen2: "/productos/boxy-energy-2.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Boxy Lost",
        precio: "$19.000",
        imagen: "/productos/boxy-lost.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Boxy Love Saint Tela Deportiva",
        precio: "$15.000",
        imagen: "/productos/boxy-love-saint-tela-deportiva-1.jpeg",
        imagen2: "/productos/boxy-love-saint-tela-deportiva-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Boxy Nevada",
        precio: "$20.500",
        imagen: "/productos/boxy-nevada.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Boxy New Life",
        precio: "$24.000",
        imagen: "/productos/boxy-new-life-1.jpeg",
        imagen2: "/productos/boxy-new-life-2.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Clasica Billabong",
        precio: "$22.000",
        imagen: "/productos/clasica-billabong-1.jpeg",
        imagen2: "/productos/clasica-billabong-2.jpeg",
        talles: "XXL",
    },
    {
        categoria: "Remeras",
        nombre: "Over Grave",
        precio: "$19.000",
        imagen: "/productos/over-grave.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Over Luck this",
        precio: "$19.000",
        imagen: "/productos/remera-over-luck-this-1.jpeg",
        imagen2: "/productos/remera-over-luck-this-2.jpeg",
        talles: "l",
    },
    {
        categoria: "Remeras",
        nombre: "Over Liso Blue",
        precio: "$18.000",
        imagen: "/productos/over-liso-blue.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Over Liso White",
        precio: "$18.000",
        imagen: "/productos/over-liso-white.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Over Liso Color Petroleo",
        precio: "$18.000",
        imagen: "/productos/over-liso-color-petroleo.jpeg",
        talles: "XXL",
    },
    {
        categoria: "Remeras",
        nombre: "Over Nevada Lisa",
        precio: "$20.500",
        imagen: "/productos/over-nevada-lisa.jpeg",
        talles: "S",
    },
    {
        categoria: "Remeras",
        nombre: "Over Seoul",
        precio: "$19.000",
        imagen: "/productos/over-seoul-1.jpeg",
        imagen2: "/productos/over-seoul-2.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Over Chateau",
        precio: "$19.000",
        imagen: "/productos/over-chateau-1.jpeg",
        imagen2: "/productos/over-chateau-2.jpeg",
        talles: "XXL",
    },
    {
        categoria: "Remeras",
        nombre: "Over Every Day",
        precio: "$19.000",
        imagen: "/productos/over-every-day-1.jpeg",
        imagen2: "/productos/over-every-day-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Over Fratar Cuello V",
        precio: "$19.000",
        imagen: "/productos/over-fratar-cuello-v.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Over Vans",
        precio: "$22.000",
        imagen: "/productos/over-vans.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Remera Clasica Rusty",
        precio: "$22.000",
        imagen: "/productos/remera-clasica-rusty-1.jpeg",
        imagen2: "/productos/remera-clasica-rusty-2.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Remera Clasica Volcome",
        precio: "$22.000",
        imagen: "/productos/remera-clasica-volcome-1.jpeg",
        imagen2: "/productos/remera-clasica-volcome-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Remera Regular Breath",
        precio: "$19.000",
        imagen: "/productos/remera-regular-breath-1.jpeg",
        imagen2: "/productos/remera-regular-breath-2.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Remera Regular Culture",
        precio: "$19.000",
        imagen: "/productos/remera-regular-culture-1.jpeg",
        imagen2: "/productos/remera-regular-culture-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Remera Regular Is Just",
        precio: "$19.000",
        imagen: "/productos/remera-regular-is-just.jpeg",
        talles: "XL",
    },
    {
        categoria: "Remeras",
        nombre: "Vans Rayada Corte Clasico",
        precio: "$22.000",
        imagen: "/productos/vans-rayada-corte-clasico.jpeg",
        talles: "S",
    },
    {
        categoria: "Remeras",
        nombre: "Remera Over Amalgama",
        precio: "$19.000",
        imagen: "/productos/over-amalgama-1.jpeg",
        imagen2: "/productos/over-amalgama-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Over Glost",
        precio: "$19.000",
        imagen: "/productos/over-glost-1.jpeg",
        imagen2: "/productos/over-glost-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Remera Regular Original",
        precio: "$19.000",
        imagen: "/productos/remera-regular-original-1.jpeg",
        imagen2: "/productos/remera-regular-original-2.jpeg",
        talles: "XXL",
    },
    {
        categoria: "Remeras",
        nombre: "Remera Regular Vectory",
        precio: "$19.000",
        imagen: "/productos/remera-regular-vectory-1.jpeg",
        imagen2: "/productos/remera-regular-vectory-2.jpeg",
        talles: "S",
    },
    {
        categoria: "Gorras",
        nombre: "Gorra New York Azul",
        precio: "$12.500",
        imagen: "/productos/gorra-new-york-azul.jpeg",
        talles: "Talle único",
    },
    {
        categoria: "Gorras",
        nombre: "Gorra New York",
        precio: "$12.500",
        imagen: "/productos/gorra-new-york.jpeg",
        talles: "Talle único",
    },
    {
        categoria: "Gorras",
        nombre: "Gorra Boston",
        precio: "$12.500",
        imagen: "/productos/gorra-boston.jpeg",
        talles: "Talle único",
    },
    {
        categoria: "Gorras",
        nombre: "Gorra Alo",
        precio: "$12.500",
        imagen: "/productos/gorra-alo.jpeg",
        talles: "Talle único",
    },
    {
        categoria: "Gorras",
        nombre: "Gorra Lisa",
        precio: "$10.000",
        imagen: "/productos/gorra-lisa.jpeg",
        talles: "Talle único",
    },
    {
        categoria: "Buzos",
        nombre: "Sweter Plush Gris",
        precio: "$22.500",
        imagen: "/productos/sweter-plush-gris.jpeg",
        talles: "XL",
    },
    {
        categoria: "Buzos",
        nombre: "Sweter Plush Marrón",
        precio: "$22.500",
        imagen: "/productos/sweter-plush-marron.jpeg",
        talles: "L",
    },
    {
        categoria: "Buzos",
        nombre: "Sweter Plush Bordó",
        precio: "$22.500",
        imagen: "/productos/sweter-plush-bordo.jpeg",
        talles: "M",
    },
    {
        categoria: "Jeans",
        nombre: "Jogger Mom Frizado",
        precio: "$30.000",
        imagen: "/productos/jogger-mom-frizado.jpeg",
        talles: "3",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Clasico Driver Forever",
        precio: "$40.000",
        imagen: "/productos/buzo-clasico-driver-forever.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Clasico Rip Curl",
        precio: "$40.000",
        imagen: "/productos/buzo-clasico-rip-curl-1.jpeg",
        imagen2: "/productos/buzo-clasico-rip-curl-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over Royals",
        precio: "$40.000",
        imagen: "/productos/buzo-over-royals-1.jpeg",
        imagen2: "/productos/buzo-over-royals-2.jpeg",
        talles: "S",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over San Francisco",
        precio: "$40.000",
        imagen: "/productos/buzo-over-san-francisco.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "camiseta argentina alternativa",
        precio: "$26.000",
        imagen: "/productos/camiseta-argentina-alternativa.jpeg",
        talles: "s,m,xl,xxl",
    },
    {
        categoria: "Remeras",
        nombre: "camiseta argentina titular",
        precio: "$26.000",
        imagen: "/productos/camiseta-argentina-titular.jpeg",
        talles: "s,m,xl,xxl",
    },
    {
        categoria: "Jeans",
        nombre: "Jogging Baggy Bordó",
        precio: "$35.000",
        imagen: "/productos/jogging-baggy-bordo.jpeg",
        talles: "S",
    },
    {
        categoria: "Jeans",
        nombre: "Jogging Baggy Gris Perla",
        precio: "$35.000",
        imagen: "/productos/jogging-baggy-gris-perla.jpeg",
        talles: "L",
    },
    {
        categoria: "Jeans",
        nombre: "Jogging Baggy Negro",
        precio: "$35.000",
        imagen: "/productos/jogging-baggy-negro.jpeg",
        talles: "M",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Black Recortes",
        precio: "$39.000",
        imagen: "/productos/baggy-black-recortes.jpeg",
        talles: "44",
    },
    {
        categoria: "Jeans",
        nombre: "Jogging Mom Chicago",
        precio: "$26.000",
        imagen: "/productos/jogging-mom-chicago.jpeg",
        talles: "M",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Celeste",
        precio: "$39.000",
        imagen: "/productos/baggy-celeste.jpeg",
        talles: "46",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Celim",
        precio: "$39.000",
        imagen: "/productos/baggy-celim.jpeg",
        talles: "44",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Nevado Gris",
        precio: "$39.000",
        imagen: "/productos/baggy-nevado-gris.jpeg",
        talles: "44,46",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Oxido",
        precio: "$39.000",
        imagen: "/productos/baggy-oxido.jpeg",
        talles: "46",
    },
    {
        categoria: "Jeans",
        nombre: "Mom Azul Liso",
        precio: "$39.000",
        imagen: "/productos/mom-azul-liso.jpeg",
        talles: "44",
    },
    {
        categoria: "Jeans",
        nombre: "Mom Nevado Azul",
        precio: "$39.000",
        imagen: "/productos/mom-nevado-azul.jpeg",
        talles: "42",
    },
    {
        categoria: "Jeans",
        nombre: "Semmi Baggy Roturas",
        precio: "$39.000",
        imagen: "/productos/semmi-baggy-roturas.jpeg",
        talles: "40,42",
    },
    {
        categoria: "Jeans",
        nombre: "Jeans Mom Gris Nevado",
        precio: "$39.000",
        imagen: "/productos/jeans-mom-gris-nevado.jpeg",
        talles: "40",
    },
    {
        categoria: "Jeans",
        nombre: "Jeans Semi Baggy Óxido",
        precio: "$39.000",
        imagen: "/productos/jeans-semi-baggy-oxido.jpeg",
        talles: "42",
    },
    {
        categoria: "Jeans",
        nombre: "Jeans Semi Baggy Cargo Óxido",
        precio: "$39.000",
        imagen: "/productos/semi-baggy-cargo-oxido.jpeg",
        talles: "38",
    },
    {
        categoria: "Jeans",
        nombre: "Jeans Baggy Costuras",
        precio: "$39.000",
        imagen: "/productos/semi-baggy-costuras.jpeg",
        talles: "38",
    },
    {
        categoria: "Jeans",
        nombre: "Jeans Semi Baggy Costuras Choco",
        precio: "$39.000",
        imagen: "/productos/semi-baggy-costuras-chocolate.jpeg",
        talles: "38",
    },
    {
        categoria: "Jeans",
        nombre: "Jeans Semi Baggy Gris Nevado Pinzas",
        precio: "$39.000",
        imagen: "/productos/semi-baggy-gris-nevado-pinzas-al-costado.jpeg",
        talles: "38",
    },
    {
        categoria: "Jeans",
        nombre: "Jeans Semi Baggy Gris Oscuro",
        precio: "$39.000",
        imagen: "/productos/semi-baggy-gris-oscuro.jpeg",
        talles: "38",
    },
    {
        categoria: "Jeans",
        nombre: "Jeans Semi Baggy Camuflado",
        precio: "$39.000",
        imagen: "/productos/semi-baggy-camuflado-blue.jpeg",
        talles: "38",
    },
];