export const productos = [
    {
        categoria: "Jeans",
        nombre: "Baggy Azul Clasico",
        precio: "$39.000",
        imagen: "/productos/baggy-azul-clasico.jpeg",
        talles: "38, 42",
    },
    {
        categoria: "Jeans",
        nombre: "Jogging Baggy Bordo",
        precio: "$35.000",
        imagen: "/productos/jogging-baggy-bordo.jpeg",
        talles: "38",
    },
    {
        categoria: "Jeans",
        nombre: "Semy Baggy Azul",
        precio: "$39.000",
        imagen: "/productos/Semi-Baggy-azul.jpeg",
        talles: "38,40",
    },
    {
        categoria: "Jeans",
        nombre: "Semy Baggy Beige",
        precio: "$39.000",
        imagen: "/productos/semi-baggy-beige.jpeg",
        talles: "38",
    },
    {
        categoria: "Jeans",
        nombre: "Semy Baggy Gris Carbon",
        precio: "$39.000",
        imagen: "/productos/Semi-baggy-gris-Carbon.jpeg",
        talles: "38,40",
    },
     {
        categoria: "Jeans",
        nombre: "Semy Baggy Oxido",
        precio: "$39.000",
        imagen: "/productos/Semi-baggy-óxido.jpeg",
        talles: "38,40",
    },
     {
        categoria: "Jeans",
        nombre: "Semy Baggy Total Black",
        precio: "$39.000",
        imagen: "/productos/Semi-Baggy-total-black.jpeg",
        talles: "38,40",
    },
    {
        categoria: "Jeans",
        nombre: "Semy Baggy Gris perla",
        precio: "$39.000",
        imagen: "/productos/Semi-Baggy-gris-perla.jpeg",
        talles: "38,42",
    },
    {
        categoria: "Jeans",
        nombre: "Jogging Baggy Gris Perla",
        precio: "$35.000",
        imagen: "/productos/jogging-baggy-gris-perla.jpeg",
        talles: "L",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Black Recortes",
        precio: "$39.000",
        imagen: "/productos/baggy-black-recortes.jpeg",
        talles: "44",
    },
    {
        categoria: "Jeans",
        nombre: "Jogging Mom Chicago",
        precio: "$26.000",
        imagen: "/productos/jogging-mom-chicago.jpeg",
        talles: "40",
    },
    {
        categoria: "Jeans",
        nombre: "Jogging Recto",
        precio: "$30.000",
        imagen: "/productos/joggin-recto-negro.jpeg",
        talles: "42,44",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Nevado Gris",
        precio: "$39.000",
        imagen: "/productos/baggy-nevado-gris.jpeg",
        talles: "44,46",
    },
    {
        categoria: "Jeans",
        nombre: "Mom Nevado Azul",
        precio: "$39.000",
        imagen: "/productos/mom-nevado-azul.jpeg",
        talles: "44",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Localizado",
        precio: "$39.000",
        imagen: "/productos/baggy-localizado.jpeg",
        talles: "42",
    },
    {
        categoria: "Jeans",
        nombre: "Semmi Baggy Roturas",
        precio: "$39.000",
        imagen: "/productos/semmi-baggy-roturas.jpeg",
        talles: "40,42",
    },
    {
        categoria: "Jeans",
        nombre: "Jeans Semi Baggy Óxido",
        precio: "$39.000",
        imagen: "/productos/jeans-semi-baggy-oxido.jpeg",
        talles: "42",
    },
    {
        categoria: "Jeans",
        nombre: "Jeans Semi Baggy Cargo Óxido",
        precio: "$39.000",
        imagen: "/productos/semi-baggy-cargo-oxido.jpeg",
        talles: "38",
    },
    {
        categoria: "Jeans",
        nombre: "Jeans Semi Baggy Costuras Choco",
        precio: "$39.000",
        imagen: "/productos/semi-baggy-costuras-chocolate.jpeg",
        talles: "38",
    },
    {
        categoria: "Jeans",
        nombre: "Jeans Semi Baggy Gris Nevado Pinzas",
        precio: "$39.000",
        imagen: "/productos/semi-baggy-gris-nevado-pinzas-al-costado.jpeg",
        talles: "38",
    },
    {
        categoria: "Jeans",
        nombre: "Jeans Semi Baggy Gris Oscuro",
        precio: "$39.000",
        imagen: "/productos/semi-baggy-gris-oscuro.jpeg",
        talles: "40,44",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Celeste",
        precio: "$39.000",
        imagen: "/productos/baggy-celeste-liso.jpeg",
        talles: "40",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Prototipe",
        precio: "$39.000",
        imagen: "/productos/baggy-prototipe.jpeg",
        talles: "40",
    },
    {
        categoria: "Jeans",
        nombre: "Joggin Baggy",
        precio: "$35.000",
        imagen: "/productos/joggin-baggy.jpeg",
        talles: "40,42",
    },
    {
        categoria: "Jeans",
        nombre: "Mom Celeste",
        precio: "$39.000",
        imagen: "/productos/mom-celeste.jpeg",
        talles: "42",
    },
    {
        categoria: "Jeans",
        nombre: "Mom Localizado",
        precio: "$39.000",
        imagen: "/productos/mom-localizado.jpeg",
        talles: "40",
    },
    {
        categoria: "Jeans",
        nombre: "Jogger Mom Frizado",
        precio: "$30.000",
        imagen: "/productos/jogger-mom-frizado.jpeg",
        talles: "L",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Celeste",
        precio: "$39.000",
        imagen: "/productos/baggy-celeste.jpeg",
        talles: "46",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Black",
        precio: "$39.000",
        imagen: "/productos/baggy-black.jpeg",
        talles: "42",
    },
    {
        categoria: "Jeans",
        nombre: "Recto Black",
        precio: "$39.000",
        imagen: "/productos/jeans-recto-black.jpeg",
        talles: "42",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Bolsillos Bordados",
        precio: "$39.000",
        imagen: "/productos/baggy-bolsillos-bordados-1.jpeg",
        imagen2: "/productos/baggy-bolsillos-bordados-2.jpeg",
        talles: "40",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Cargo Azul Nevado",
        precio: "$39.000",
        imagen: "/productos/baggy-cargo-azul-nevado.jpeg",
        talles: "40",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Costuras Blancas",
        precio: "$39.000",
        imagen: "/productos/baggy-costuras-blancas.jpeg",
        talles: "42",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Cruz",
        precio: "$39.000",
        imagen: "/productos/baggy-cruz.jpeg",
        talles: "40",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Gabardina Beige",
        precio: "$39.000",
        imagen: "/productos/baggy-gabardina-beige.jpeg",
        talles: "40",
    },
    {
        categoria: "Jeans",
        nombre: "Baggy Localizado Bigotes",
        precio: "$39.000",
        imagen: "/productos/baggy-localizado-bigotes.jpeg",
        talles: "40",
    },
     {
        categoria: "Buzos",
        nombre: "Buzo Brakeli Rustico ",
        precio: "$22.000",
        imagen: "/productos/buzo-brakeli-s.jpeg",
        imagen2: "/productos/buzo-brakeli-s-2.jpeg",
        talles: "S",
    },
     {
        categoria: "Buzos",
        nombre: "Buzo Prestige Rustico ",
        precio: "$22.000",
        imagen: "/productos/buzo-prestige-m.jpeg",
        imagen2: "/productos/buzo-prestige-m-2.jpeg",
        talles: "M",
    },
      {
        categoria: "Buzos",
        nombre: "Buzo Ever ",
        precio: "$25.000",
        imagen: "/productos/buzo-ever-m.jpeg",
        imagen2: "/productos/buzo-ever-m-2.jpeg",
        talles: "L",
    },
     {
        categoria: "Buzos",
        nombre: "Buzo Freedom",
        precio: "$30.000",
        imagen: "/productos/buzo-freedom-m.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo iDGAF",
        precio: "$35.000",
        imagen: "/productos/buzo-idgaf-m.jpeg",
        imagen2: "/productos/buzo-idgaf-m-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo King",
        precio: "$35.000",
        imagen: "/productos/buzo-king-m.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Boxy Gris",
        precio: "$40.000",
        imagen: "/productos/buzo-boxy-gris.jpeg",
        talles: "L",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Boxy Total Black",
        precio: "$40.000",
        imagen: "/productos/buzo-boxy-total-black.jpeg",
        talles: "S, M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Clasico Rip Curl",
        precio: "$40.000",
        imagen: "/productos/buzo-clasico-rip-curl-1.jpeg",
        imagen2: "/productos/buzo-clasico-rip-curl-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Corazon",
        precio: "$35.000",
        imagen: "/productos/buzo-corazon.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over Blossom",
        precio: "$38.000",
        imagen: "/productos/buzo-over-blossom.jpeg",
        talles: "S",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over La",
        precio: "$40.000",
        imagen: "/productos/buzo-over-la.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over New York 99",
        precio: "$40.000",
        imagen: "/productos/buzo-over-new-york-99-1.jpeg",
        imagen2: "/productos/buzo-over-new-york-99-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over Ne",
        precio: "$34.000",
        imagen: "/productos/buzo-over-ne-1.jpeg",
        imagen2: "/productos/buzo-over-ne-2.jpeg",
        talles: "XL",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over Myself",
        precio: "$40.000",
        imagen: "/productos/buzo-over-myself.jpeg",
        talles: "L",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over Rosa",
        precio: "$35.000",
        imagen: "/productos/buzo-over-rosa-1.jpeg",
        imagen2: "/productos/buzo-over-rosa-2.jpeg",
        talles: "S",
    },
    {
        categoria: "Buzos",
        nombre: "Sweter Plush Gris",
        precio: "$22.500",
        imagen: "/productos/sweter-plush-gris.jpeg",
        talles: "XL",
    },
    {
        categoria: "Buzos",
        nombre: "Sweter Plush Marron",
        precio: "$22.500",
        imagen: "/productos/sweter-plush-marron.jpeg",
        talles: "L",
    },
    {
        categoria: "Buzos",
        nombre: "boxy Black",
        precio: "$40.000",
        imagen: "/productos/boxy-black.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Be Kind",
        precio: "$40.000",
        imagen: "/productos/buzo-bekind.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Sweter White",
        precio: "$22.500",
        imagen: "/productos/sweter-white.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Boxy Nevado",
        precio: "$22.500",
        imagen: "/productos/buzo-boxy-nevado.jpeg",
        talles: "M",
    },
     {
        categoria: "Buzos",
        nombre: "Buzo Cuello Redondo Bordo",
        precio: "$40.000",
        imagen: "/productos/buzo-cuello-redondo-bordo.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Cuello Redondo Gris Perla",
        precio: "$40.000",
        imagen: "/productos/buzo-cuello-redondo-gris-perla.jpeg",
        talles: "S",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Cuello Redondo",
        precio: "$40.000",
        imagen: "/productos/buzo-cuello-redondo.jpeg",
        talles: "S",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over Black",
        precio: "$40.000",
        imagen: "/productos/buzo-over-black.jpeg",
        imagen2: "/productos/buzo-over-black-1.jpeg",
        talles: "S",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Clasico London",
        precio: "$35.000",
        imagen: "/productos/buzo-clasico-london-1.jpeg",
        imagen2: "/productos/buzo-clasico-london-2.jpeg",
        talles: "L",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over Espina",
        precio: "$40.000",
        imagen: "/productos/buzo-over-espina-1.jpeg",
        imagen2: "/productos/buzo-over-espina-2.jpeg",
        talles: "M",
    },
     {
        categoria: "Buzos",
        nombre: "Buzo Over Seven",
        precio: "$35.000",
        imagen: "/productos/buzo-over-seven-1.jpeg",
        imagen2: "/productos/buzo-over-seven-2.jpeg",
        talles: "XXL",
    },
     {
        categoria: "Buzos",
        nombre: "Buzo Over White",
        precio: "$38.000",
        imagen: "/productos/buzo-over-white.jpeg",
        talles: "S",
    },
    {
        categoria: "Buzos",
        nombre: "Buzo Over crem",
        precio: "$38.000",
        imagen: "/productos/buzo-over-crema.jpeg",
        talles: "S",
    },
     {
        categoria: "Buzos",
        nombre: "Buzo Over Wonder",
        precio: "$40.000",
        imagen: "/productos/buzo-over-wonder.jpeg",
        talles: "S",
    },
    {
        categoria: "Buzos",
        nombre: "campera crema",
        precio: "$40.000",
        imagen: "/productos/campera-white.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Sweter White",
        precio: "$22.500",
        imagen: "/productos/sweter-white.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Campera Camuflada Semi Jeans",
        precio: "$45.000",
        imagen: "/productos/campera-camuflada-semi-jeans.jpeg",
        talles: "M",
    },
    {
        categoria: "Buzos",
        nombre: "Campera Reversible",
        precio: "$50.000",
        imagen: "/productos/campera-reversible-1.jpeg",
        imagen2: "/productos/campera-reversible-2.jpeg",
        talles: "S",
    },
    {
        categoria: "Buzos",
        nombre: "Campera Bomber Boxy",
        precio: "$40.000",
        imagen: "/productos/campera-bomber-boxy-jeans-1.jpeg",
        imagen2: "/productos/campera-bomber-boxy-jeans-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Chomba Boxy Alemania",
        precio: "$25.000",
        imagen: "/productos/chomba-boxy-alemania.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Chomba Boxy Good",
        precio: "$25.000",
        imagen: "/productos/chomba-boxy-good.jpeg",
        talles: "S",
    },
    {
        categoria: "Remeras",
        nombre: "Chomba Boxy Portugal",
        precio: "$25.000",
        imagen: "/productos/chomba-boxy-portugal.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Chomba Boxy Algodon Chnyouu",
        precio: "$24.000",
        imagen: "/productos/chomba-boxy-algodon-chnyouu.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Boxy 2023",
        precio: "$18.000",
        imagen: "/productos/boxy-2023.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Boxy Corazon",
        precio: "$24.000",
        imagen: "/productos/boxy-corazon-1.jpeg",
        imagen2: "/productos/boxy-corazon-2.jpeg",
        talles: "S",
    },
    {
        categoria: "Remeras",
        nombre: "Boxy Emestudios",
        precio: "$19.000",
        imagen: "/productos/boxy-emestudios.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Boxy Energy",
        precio: "$19.000",
        imagen: "/productos/boxy-energy-1.jpeg",
        imagen2: "/productos/boxy-energy-2.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Boxy Lost",
        precio: "$19.000",
        imagen: "/productos/boxy-lost.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Boxy Love Saint Tela Deportiva",
        precio: "$15.000",
        imagen: "/productos/boxy-love-saint-tela-deportiva-1.jpeg",
        imagen2: "/productos/boxy-love-saint-tela-deportiva-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Boxy Nevada",
        precio: "$20.500",
        imagen: "/productos/boxy-nevada.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Over Grave",
        precio: "$19.000",
        imagen: "/productos/over-grave.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Over Luck this",
        precio: "$19.000",
        imagen: "/productos/remera-over-luck-this-1.jpeg",
        imagen2: "/productos/remera-over-luck-this-2.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Over Liso Blue",
        precio: "$18.000",
        imagen: "/productos/over-liso-blue.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Over Liso White",
        precio: "$18.000",
        imagen: "/productos/over-liso-white.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Over Nevada Lisa",
        precio: "$20.500",
        imagen: "/productos/over-nevada-lisa.jpeg",
        talles: "S",
    },
    {
        categoria: "Remeras",
        nombre: "Over Chateau",
        precio: "$19.000",
        imagen: "/productos/over-chateau-1.jpeg",
        imagen2: "/productos/over-chateau-2.jpeg",
        talles: "XXL",
    },
    {
        categoria: "Remeras",
        nombre: "Over Every Day",
        precio: "$19.000",
        imagen: "/productos/over-every-day-1.jpeg",
        imagen2: "/productos/over-every-day-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Over Fratar Cuello V",
        precio: "$19.000",
        imagen: "/productos/over-fratar-cuello-v.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Over Vans",
        precio: "$22.000",
        imagen: "/productos/over-vans.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Remera Clasica Rusty",
        precio: "$22.000",
        imagen: "/productos/remera-clasica-rusty-1.jpeg",
        imagen2: "/productos/remera-clasica-rusty-2.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Remera Clasica Volcome",
        precio: "$22.000",
        imagen: "/productos/remera-clasica-volcome-1.jpeg",
        imagen2: "/productos/remera-clasica-volcome-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Remera Regular Breath",
        precio: "$19.000",
        imagen: "/productos/remera-regular-breath-1.jpeg",
        imagen2: "/productos/remera-regular-breath-2.jpeg",
        talles: "L",
    },
    {
        categoria: "Remeras",
        nombre: "Remera Regular Culture",
        precio: "$19.000",
        imagen: "/productos/remera-regular-culture-1.jpeg",
        imagen2: "/productos/remera-regular-culture-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Remera Regular Is Just",
        precio: "$19.000",
        imagen: "/productos/remera-regular-is-just.jpeg",
        talles: "XL",
    },
    {
        categoria: "Remeras",
        nombre: "Vans Rayada Corte Clasico",
        precio: "$22.000",
        imagen: "/productos/vans-rayada-corte-clasico.jpeg",
        talles: "S",
    },
    {
        categoria: "Remeras",
        nombre: "Remera Over Amalgama",
        precio: "$19.000",
        imagen: "/productos/over-amalgama-1.jpeg",
        imagen2: "/productos/over-amalgama-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Remeras",
        nombre: "Over Glost",
        precio: "$19.000",
        imagen: "/productos/over-glost-1.jpeg",
        imagen2: "/productos/over-glost-2.jpeg",
        talles: "M",
    },
    {
        categoria: "Accesorios",
        nombre: "Gorra New York Azul",
        precio: "$12.500",
        imagen: "/productos/gorra-new-york-azul.jpeg",
    },
    {
        categoria: "Accesorios",
        nombre: "Gorra New York",
        precio: "$12.500",
        imagen: "/productos/gorra-new-york.jpeg",
    },
    {
        categoria: "Accesorios",
        nombre: "Gorra Boston",
        precio: "$12.500",
        imagen: "/productos/gorra-boston.jpeg",
    },
    {
        categoria: "Accesorios",
        nombre: "Gorra Lisa",
        precio: "$10.000",
        imagen: "/productos/gorra-lisa.jpeg",
    },
    {
        categoria: "Accesorios",
        nombre: "Gorra Alo",
        precio: "$12.500",
        imagen: "/productos/gorra-alo.jpeg",
    },
    {
        categoria: "Accesorios",
        nombre: "Gorra Palmera",
        precio: "$12.500",
        imagen: "/productos/gorra-palmera.jpeg",
    },
    {
        categoria: "Accesorios",
        nombre: "Morral Impermeable",
        precio: "$24.000",
        imagen: "/productos/morral-impermeable.jpeg",
    },
    {
        categoria: "Accesorios",
        nombre: "Rinonera Impermeable",
        precio: "$22.500",
        imagen: "/productos/riñonera-impermeable.jpeg",
    },
    {
        categoria: "Accesorios",
        nombre: "9PM 100ML",
        precio: "$45.000",
        imagen: "/productos/9pm.jpeg",
        descripcion: "comienza con una salida frutal, lijeramete especiada, vainilla cremosa acompañada de haba tonka, llamativo juvenil exelente duracion, recomedado para uso de noche.",
    },
    {
        categoria: "Accesorios",
        nombre: "Elysian Fields 100ML",
        precio: "$32.000",
        imagen: "/productos/Elysian-fields.jpeg",
        descripcion: "frutas suaves y un fondo cemoso de almizcle. tiene sensacion de limpieza y elegancia, uso diario.",
    },
    {
        categoria: "Accesorios",
        nombre: "Hawas Black 100ML",
        precio: "$40.000",
        imagen: "/productos/Hawas-black.jpeg",
        descripcion: "Es una fragancia intensa, elegante y masculina. tiene un  aire misterioso con un toque ahumado y amaderado. ideal para quienes buscan destacar sin ser exesivamente dulce..",
    },
    {
        categoria: "Accesorios",
        nombre: "Hawas Malibu 100ML",
        precio: "$40.000",
        imagen: "/productos/Hawas-Malibú.jpeg",
        descripcion: "Acuatica,citrica y fresca. limpio y refrescante, transmite sensacion de recien bañado y brisa marina, uso todo el dia..",
    },
     {
        categoria: "Accesorios",
        nombre: "Hawas Tropical 100ML",
        precio: "$40.000",
        imagen: "/productos/Hawas-tropical.jpeg",
        descripcion: "Muy fresco, alegre y veraniego. da la sensacion de una bebida tropical en la playa. es dulce, pero mantiene una buena frescura, uso diario.",
    },
     {
        categoria: "Accesorios",
        nombre: "Odyssey Aqua 100ML",
        precio: "$40.000",
        imagen: "/productos/Odyssey-aqua.jpeg",
        descripcion: "Es un peRfume extremadamete fesco, limpio y elegante. abre con citricos vibrantes y notas marinas que transmiten sesacion de recien salido de la ducha, a medida que se seca aparecen maderas suaves y almizcles que le dan mayor duracion. uso diario.",
    },
    {
        categoria: "Accesorios",
        nombre: "Kit Ocean",
        precio: "$16.000",
        imagen: "/productos/kit-ocean-30ml-y-30gr.jpeg",
        descripcion: "Aroma fresco y marino. Incluye perfume 30ml y gel de ducha 30gr, ideal para uso diario.",
    },
     {
        categoria: "Accesorios",
        nombre: "Asad Lattafa",
        precio: "$38.000",
        imagen: "/productos/asad-chocolate.jpeg",
        descripcion: "100ml",
    },
     {
        categoria: "Accesorios",
        nombre: "Perfume Toscano 80ML",
        precio: "$38.500",
        imagen: "/productos/perf-toscano.jpeg",
        descripcion: "Un aroma intenso donde el cuero es protagonista, esta acompañado por azafran, madera y un toque ahumado, que transmite lujo y mucha personalidad",
    },
    {
        categoria: "Accesorios",
        nombre: "Perfume Velvet 80ML",
        precio: "$28.500",
        imagen: "/productos/perf-velvet.jpeg",
        imagen2: "/productos/perf-velvet-2.jpeg",
        descripcion: "Es un perfume profundo y envolvente. convina el oud con cuero, ambar y notas amaderadas creando un aroma calido, elgante y duradero ideal para uso de noche",
    },
    {
        categoria: "Accesorios",
        nombre: "Fakhar Lattafa",
        precio: "$30.000",
        imagen: "/productos/fakhar-latfafa-70-ml.jpeg",
        descripcion: "Fragancia arabe moderna con notas frescas, especiadas y amaderadas, 70ml.",
    },
    {
        categoria: "Accesorios",
        nombre: "Ameerat Al Arab",
        precio: "$40.000",
        imagen: "/productos/ameerat-al-arab-ara-100-ml.jpeg",
        descripcion: "Fragancia arabe sofisticada con excelente presencia y larga duracion, 100ml.",
    },
    {
        categoria: "Accesorios",
        nombre: "Aimen",
        precio: "$20.000",
        imagen: "/productos/aimen-100-ml.jpeg",
        descripcion: "Aroma equilibrado y elegante, ideal para uso diario y ocasiones especiales,100ml.",
    },
    {
        categoria: "Accesorios",
        nombre: "Hawas Fire",
        precio: "$38.000",
        imagen: "/productos/perf-hawas-fire.jpeg",
        descripcion: "100ml.",
    },
    {
        categoria: "Accesorios",
        nombre: "Insuperable",
        precio: "$22.000",
        imagen: "/productos/perf-insuperable.jpeg",
        descripcion: "100ml.",
    },
     {
        categoria: "Accesorios",
        nombre: "Inversion",
        precio: "$22.000",
        imagen: "/productos/perf-inversion.jpeg",
        descripcion: "100ml.",
    },
    {
        categoria: "Accesorios",
        nombre: "Sapphire Sky 100ml",
        precio: "$35.000",
        imagen: "/productos/sapphire-sky.jpeg",
        descripcion: "100ml.",
    },
    {
        categoria: "Accesorios",
        nombre: "Rosed Ahar",
        precio: "$20.000",
        imagen: "/productos/rosed-ahar-100-ml.jpeg",
        descripcion: "Fragancia con notas florales y dulces que aportan frescura y personalidad,100ml.",
    },
    {
        categoria: "Accesorios",
        nombre: "Gorro Boston",
        precio: "$14.500",
        imagen: "/productos/gorro-boston.jpeg",
        descripcion: "Gorros de hilo con logo Bordoo.",
    },
    {
        categoria: "Accesorios",
        nombre: "Gorro New Orleans",
        precio: "$14.500",
        imagen: "/productos/gorro-new-orleans.jpeg",
        descripcion: "Gorros de hilo con logo Bordoo.",
    },
    {
        categoria: "Accesorios",
        nombre: "Reloj Digital Resistente al Agua",
        precio: "$22.500",
        imagen: "/productos/reloj-digital-recistente-al-agua-black-1.jpeg",
        imagen2: "/productos/reloj-digital-recistente-al-agua-black-2.jpeg",
        descripcion: "Resistente al agua, sumergible hasta 10min",
    },
    {
        categoria: "Accesorios",
        nombre: "Reloj Digital Resistente al Agua Rojo",
        precio: "$22.500",
        imagen: "/productos/reloj-digital-recistente-al-agua-rojo-1.jpeg",
        imagen2: "/productos/reloj-digital-recistente-al-agua-rojo-2.jpeg",
        descripcion: "Resistente al agua, sumergible hasta 10min",
    },
    {
        categoria: "Accesorios",
        nombre: "Reloj clasico",
        precio: "$20.000",
        imagen: "/productos/reloj-analogico.jpeg",
        descripcion: "malla metalica",
    },
    {
        categoria: "Accesorios",
        nombre: "Cintos",
        precio: "$15.000",
        imagen: "/productos/cinto 1.jpeg",
        imagen2: "/productos/cinto 2.jpeg",
        imagen3: "/productos/cinto 3.jpeg",
        imagen4: "/productos/cinto 4.jpeg",
        descripcion: "Cintos de cuero con hebilla metalica.",
    },
     {
        categoria: "Zapatillas",
        nombre: "Adidas Forum Black",
        precio: "$70.000",
        imagen: "/productos sneakers/adidas-forum-black.jpeg",
        imagen2: "/productos sneakers/adidas-forum-black-1.jpeg",
        imagen3: "/productos sneakers/adidas-forum-black-2.jpeg",
        talles: "38,40",
    },
     {
        categoria: "Zapatillas",
        nombre: "Adidas Forum Gris",
        precio: "$65.000",
        imagen: "/productos sneakers/adidas-forum-blanca-gris.jpeg",
        talles: "40",
    },
     {
        categoria: "Zapatillas",
        nombre: "Adidas Samba Clasic",
        precio: "$65.000",
        imagen: "/productos sneakers/adidas-samba-clasic.jpeg",
        talles: "40",
    },
     {
        categoria: "Zapatillas",
        nombre: "Adidas Samba White",
        precio: "$65.000",
        imagen: "/productos sneakers/adidas-samba-white.jpeg",
        talles: "41",
    },
     {
        categoria: "Zapatillas",
        nombre: "Converse Clasica",
        precio: "$30.000",
        imagen: "/productos sneakers/converse-clasica.jpeg",
        talles: "39",
    },
     {
        categoria: "Zapatillas",
        nombre: "Jordan 4 Pink",
        precio: "$65.000",
        imagen: "/productos sneakers/jordan-4-pink.jpeg",
        talles: "36,37",
    },
     {
        categoria: "Zapatillas",
        nombre: "Jordan 4 Bred",
        precio: "$65.000",
        imagen: "/productos sneakers/jordan-retro-4-bred.jpeg",
        talles: "39,41",
    },
    {
        categoria: "Zapatillas",
        nombre: "Nike Sb Black",
        precio: "$65.000",
        imagen: "/productos sneakers/nike-sb-black.jpeg",
        imagen2: "/productos sneakers/nike-sb-black-1.jpeg",
        talles: "39",
    },
    {
        categoria: "Zapatillas",
        nombre: "Nike Sb Gris",
        precio: "$65.000",
        imagen: "/productos sneakers/nike-sb-gris.jpeg",
        imagen2: "/productos sneakers/nike-sb-gris-1.jpeg",
        imagen3: "/productos sneakers/nike-sb-gris-2.jpeg",
        talles: "39",
    },
     {
        categoria: "Zapatillas",
        nombre: "Nike Sb dunk Low",
        precio: "$65.000",
        imagen: "/productos sneakers/nike-sb-panda.jpeg",
        imagen2: "/productos sneakers/nike-sb-panda-1.jpeg",
        talles: "42",
    },
     {
        categoria: "Zapatillas",
        nombre: "Nike Travis Scott",
        precio: "$65.000",
        imagen: "/productos sneakers/nike-travis-scott.jpeg",
        talles: "40",
    },
     {
        categoria: "Zapatillas",
        nombre: "Puma La France",
        precio: "$70.000",
        imagen: "/productos sneakers/puma-la-france.jpeg",
        talles: "40",
    },
    {
        categoria: "Zapatillas",
        nombre: "Straye Black",
        precio: "$70.000",
        imagen: "/productos sneakers/straye-black.jpeg",
        talles: "41",
    },
    {
        categoria: "Zapatillas",
        nombre: "Vans Hylane ecocuero",
        precio: "$30.000",
        imagen: "/productos sneakers/vans-hylane-cuerina.jpeg",
        talles: "39",
    },
    {
        categoria: "Zapatillas",
        nombre: "Vans Old School",
        precio: "$30.000",
        imagen: "/productos sneakers/vans-old-school.jpeg",
        talles: "39",
    },
    {
        categoria: "Zapatillas",
        nombre: "Vans Sk8 Black",
        precio: "$65.000",
        imagen: "/productos sneakers/vans-sk8-full-black.jpeg",
        talles: "40",
    },
];

